name: GHA to run e2e test for examples
on: push

jobs:
  run-e2e-test:
    name: run e2e test on examples
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/products/zeebe/ci/zeebe-process-test REGISTRY_HUB_DOCKER_COM_USR;
            secret/data/products/zeebe/ci/zeebe-process-test REGISTRY_HUB_DOCKER_COM_PSW;
            secret/data/products/zeebe/ci/zeebe-process-test ARTIFACTS_USR;
            secret/data/products/zeebe/ci/zeebe-process-test ARTIFACTS_PSW;
            secret/data/github.com/organizations/camunda MAVEN_CENTRAL_DEPLOYMENT_USR;
            secret/data/github.com/organizations/camunda MAVEN_CENTRAL_DEPLOYMENT_PSW;
            secret/data/github.com/organizations/camunda MAVEN_CENTRAL_GPG_SIGNING_KEY_PASSPHRASE;
            secret/data/github.com/organizations/camunda MAVEN_CENTRAL_GPG_SIGNING_KEY_SEC;
            
      - name: set nodeJS version
        uses: actions/setup-node@v4
        with:
          node-version: 17
      - name: Build spring boot start - invoice example
        run: mvn spring-boot:run
        working-directory: ./spring-boot-starter/example-invoice
      - name: check out ee code
        uses: actions/checkout@v4
        with:
          repository: camunda/camunda-bpm-platform-ee
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
            args: "chrome tests"
      
      
